services:
    widget_grid_factory:
        class: Widget\Bundle\Grid\Factory
        calls:
            - [setTranslator, [@translator]]

    widget_bundle_twig_extension:
        class: Widget\Bundle\Twig\RequestExtension
        tags:
            - { name: twig.extension }